;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        ivy-alt-done
        mb/backward-delete-word
        mb/backwards-word
        mb/end-of-line
        mb/forward-word
        mb/fuse-line
        mb/quit
        mb/start-of-line
        mc/skip-to-next-like-thi
        reindent-then-newline-and-indent
        sp-kill-sexp
        sp-splice-sexp
        undo-only
        ))

(setq mc/cmds-to-run-once
      '(
        keyboard-escape-quit
        mac-mwheel-scroll
        ))
