;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mb/backwards-word
        mb/end-of-line
        mb/forward-word
        mb/start-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        keyboard-escape-quit
        ))
