(source gnu)
(source melpa)

;;; environment
(depends-on "cask")
(depends-on "exec-path-from-shell")

;;; utility
(depends-on "bind-key")
(depends-on "free-keys")
(depends-on "projectile")
(depends-on "yasnippet")
(depends-on "super-save")
(depends-on "imenu-anywhere")
(depends-on "avy")
(depends-on "smex")
(depends-on "git-timemachine")
(depends-on "ample-theme")
(depends-on "open-github-from-here" :git "http://github.com/mbriggs/emacs-open-github-from-here.git")
(depends-on "discover-my-major" :git "http://github.com/steckerhalter/discover-my-major.git")
(depends-on "etags-select")
(depends-on "neotree")
(depends-on "paradox")


;;; editor
(depends-on "highlight-numbers")
(depends-on "rainbow-identifiers")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "htmlize")
(depends-on "multiple-cursors")
(depends-on "idle-highlight-mode")
(depends-on "smartparens")
(depends-on "anzu")
(depends-on "toggle-quotes")
(depends-on "column-enforce-mode")
(depends-on "company")
(depends-on "company-statistics")
(depends-on "ace-jump-mode")
(depends-on "volatile-highlights")
(depends-on "rainbow-mode")
(depends-on "emojify")

;;; tools
(depends-on "ag")
(depends-on "magit")
(depends-on "prodigy")
(depends-on "butler")
(depends-on "slack")
(depends-on "httprepl")
(depends-on "swoop")
(depends-on "yagist")
(depends-on "diff-hl")
(depends-on "inf-mongo" :git "http://github.com/tobiassvn/inf-mongo.git")
(depends-on "yasnippet")
(depends-on "auto-yasnippet")
(depends-on "multi-term")
(depends-on "emmet-mode")

;;; searching
(depends-on "ido-vertical-mode")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "ido-hacks")
(depends-on "flx-ido")

;;; languages
(depends-on "web-mode")
(depends-on "alchemist")
(depends-on "cider")
(depends-on "tide")
(depends-on "typescript-mode")
(depends-on "highlight-cl")
(depends-on "go-mode" :git "http://github.com/dominikh/go-mode.el.git")
(depends-on "coffee-mode")
(depends-on "markdown-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")

;;; linting
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "flycheck-cask")
(depends-on "flycheck-elixir-dogma" :git "http://github.com/obmarg/flycheck-elixir-dogma.git")
(depends-on "rubocop")

;;; libs
(depends-on "dash")
(depends-on "f")
(depends-on "ht")
(depends-on "popwin")
(depends-on "s")
(depends-on "gh")

;;; ruby
(depends-on "enh-ruby-mode")
(depends-on "rbenv")
(depends-on "bundler")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "ruby-refactor")
(depends-on "inf-ruby")
(depends-on "ruby-guard")

;;; js
(depends-on "json-mode")
(depends-on "json-snatcher")
(depends-on "tern")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "js-doc")
(depends-on "company-tern")
(depends-on "deferred")
(depends-on "request")
(depends-on "websocket")
(depends-on "oauth2")
(depends-on "circe")
(depends-on "alert")
